

a="PASS 555\r\nNICK yboudoui2\r\nUSER yboudoui yboudoui localhost :Youssouf BOUDOUIA\r\nJOIN #t\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\nPRIVMSG #t :asdasd\r\n"

#nc 127.0.0.1 8080 $a

echo -n $a | nc 127.0.0.1 8082
#PRIVMSG #t :f\r\n
#EOF

